version: "3"

services:
  myspot-postgres:
    image: postgres
    shm_size: "4gb"
    container_name: myspot-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 2043:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
