@url = http://localhost:5000

@reservationId = 866b1332-7cfc-4548-9444-7a4ebf49dc38

@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations
Content-Type: application/json

{
  "parkingSpotId": "{{parkingSpotId}}",
  "EmployeeName": "John Doe",
  "LicensePlate": "XYZ123",
  "Date": "2023-08-13"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "LicensePlate": "ABC987"
}

###
DELETE {{url}}/reservations/{{reservationId}}
